name: CI

on:
  push:
    branches:
      - main
      - 2.*
  pull_request: ~

env:
  CACHE_VERSION: 4
  DEFAULT_PYTHON: 3.8
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

jobs:
  prepare-base:
    name: Create venv with virtualenv==15.1.0
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Create venv and run test case
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m pip install virtualenv==15.1.0
          python -m virtualenv venv
          . venv\scripts\activate
          which python
          python -c "import distutils.util; print(distutils.util)"
          python -m pip install pylint==2.12.2
          pylint --version
          pylint venv/test.py

