name: Test pylint

on:
  pull_request:

jobs:
  test-pylint-with-astroid-sha:
    uses: jacobtylerwalls/pylint/.github/workflows/tests.yaml@run-with-custom-astroid
    with:
      repository: pylint-dev/pylint
      astroid_sha: ${{ github.event.pull_request.head.sha }}
